version: "3"

services:

  runtime-setup:
    image: swift-cluster-membership:20.04-5.5
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.5"

  unit-tests:
    image: swift-cluster-membership:20.04-5.5

  unit-tests-until-failure:
    image: swift-cluster-membership:20.04-5.5

  integration-tests:
    image: swift-cluster-membership:20.04-5.5

  test:
    image: swift-cluster-membership:20.04-5.5

  bench:
    image: swift-cluster-membership:20.04-5.5

  shell:
    image: swift-cluster-membership:20.04-5.5

  sample-crash:
    image: swift-cluster-membership:20.04-5.5
