version: "3"

services:

  runtime-setup:
    image: swift-cluster-membership:20.04-5.8
    build:
      args:
        ubuntu_version: "focal"
        swift_version: "5.8"

  unit-tests:
    image: swift-cluster-membership:20.04-5.8

  unit-tests-until-failure:
    image: swift-cluster-membership:20.04-5.8

  integration-tests:
    image: swift-cluster-membership:20.04-5.8

  test:
    image: swift-cluster-membership:20.04-5.8

  bench:
    image: swift-cluster-membership:20.04-5.8

  shell:
    image: swift-cluster-membership:20.04-5.8

  sample-crash:
    image: swift-cluster-membership:20.04-5.8
